### ISSUE TITLE
800x480 display 

### ISSUE THREAD

**Issue by praF02** [aCallum/SafePi#2]
have you give it a try on a 800x480 display ? just checked main.py and i did see there is a script for display and i think it does not display anything on other display than the one used. Just wondering if there is any chance to be modified so ppl can running it on what display they want. Meanwhile while i type this question, i've tryed to run it on a 800x480 and it does not display anything. i'll take a look into main.py see if there is something that i can change so it runs on multiple displays.

edit:

I've tryed with an XPT2046

**Comment by aCallum** [comment]
This project currently is specific to the SSD1305 display. I've not been able to find drivers for the XPT series of displays written in Python, so it would likely require a complete rewrite in C to support a wider range of displays.

**Comment by praF02** [comment]
Got ya ! thank you for your time, and great work man ! got you a coffee 🍡

**Comment by aCallum** [comment]
Thank you!
