### ISSUE TITLE
ccxt.gateio

### ISSUE THREAD

**Issue by christophmeurer** [aCallum/SafePi#3]
Hello,

I have a problem regarding the ccxt module. If i want to start the main.py it throws the following error:
  File "main.py", line 76, in <module>
    exchange = ccxt.gateio()
AttributeError: module 'ccxt' has no attribute 'gateio'

What could be wrong? Thanks in advance!

**Comment by aCallum** [comment]
Can you ensure you have installed ccxt with pip3 (not pip) with the following command `pip3 install ccxt`. And generally make sure your have installed the various Python 3 packages with pip3. 

pip is for Python2
pip3 is for Python3

Be sure to run with `python3 main.py`

**Comment by christophmeurer** [comment]
I really don't know what was wrong, but was 100% sure that i installed ccxt with pip3. Had to set up my pi from scratch and now it's working fine. Thanks again and nice work!
