### ISSUE TITLE
Work with 3.5' 320×480 screen

### ISSUE THREAD

**Issue by D-Pyro** [aCallum/SafePi#5]
How can I make it work with larger screen?

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    disp = SSD1305.SSD1305_128_32(rst=RST, dc=DC, spi=SPI.SpiDev(SPI_PORT, SPI_DEVICE, max_speed_hz=8000000))
  File "./drivers/SPI.py", line 42, in __init__
    self._device.open(port, device)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by aCallum** [comment]
The drivers included in this project are specificly for the SSD1305 OLED GPIO Display. Other displays will require drivers specific to that display to be used in the project.
