### ISSUE TITLE
Possible to run automatically after reboot?

### ISSUE THREAD

**Issue by Necriso** [aCallum/SafePi#7]
Hi

is there an option to run the script automatically after reboot?
I found some solutions via Google but no of them works (cron @ reboot, systemd and so on).

**Comment by luziemann** [comment]
Hi!
Create a file called `/etc/systemd/system/safemoon.service`:

```
[Unit]
Description=SafeMoon Tracker
After=network.target network-online.target

[Service]
ExecStart=/usr/bin/python3 -u main.py
WorkingDirectory=/home/pi/SafePi
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```
You need to:
- set your actual username after `User=`
- set the proper path to your script in `ExecStart=`

Now you can start the service:
`systemctl start safemoon`

And automaticly get it start on boot:
`systemctl enable safemoon`

That's it ;)
